export const context = 'statisticpage'

export const GET_ALL_REPORTS_OF_TEAM = 'STATISTICPAGE/GET_ALL_REPORTS_OF_TEAM'
export const GET_ALL_REPORTS_OF_TEAM_SUCCEEDED = 'STATISTICPAGE/GET_ALL_REPORTS_OF_TEAM_SUCCEEDED'
export const GET_ALL_REPORTS_OF_TEAM_FAILED = 'STATISTICPAGE/GET_ALL_REPORTS_OF_TEAM_FAILED'
