export const context = 'profilepage'

export const GET_USER_PROFILE = 'PROFILEPAGE/GET_USER_PROFILE'
export const GET_USER_PROFILE_SUCCEEDED = 'PROFILEPAGE/GET_USER_PROFILE_SUCCEEDED'
export const GET_USER_PROFILE_FAILED = 'PROFILEPAGE/GET_USER_PROFILE_FAILED'

export const UPDATE_USER_PROFILE = 'PROFILEPAGE/UPDATE_USER_PROFILE'
export const UPDATE_USER_PROFILE_SUCCEEDED = 'PROFILEPAGE/UPDATE_USER_PROFILE_SUCCEEDED'
export const UPDATE_USER_PROFILE_FAILED = 'PROFILEPAGE/UPDATE_USER_PROFILE_FAILED'
