export const context = 'memberpage'

export const FETCH_ALL_MEMBERS_OF_TEAM = 'MEMBERPAGE/FETCH_ALL_MEMBERS_OF_TEAM'
export const FETCH_ALL_MEMBERS_OF_TEAM_SUCCEEDED = 'MEMBERPAGE/FETCH_ALL_MEMBERS_OF_TEAM_SUCCEEDED'
export const FETCH_ALL_MEMBERS_OF_TEAM_FAILED = 'MEMBERPAGE/FETCH_ALL_MEMBERS_OF_TEAM_FAILED'
