export const context = 'memberpage'

export const FETCH_ALL_MEMBERS_OF_TEAM = 'MEMBERPAGE/FETCH_ALL_MEMBERS_OF_TEAM'
export const FETCH_ALL_MEMBERS_OF_TEAM_SUCCEEDED = 'MEMBERPAGE/FETCH_ALL_MEMBERS_OF_TEAM_SUCCEEDED'
export const FETCH_ALL_MEMBERS_OF_TEAM_FAILED = 'MEMBERPAGE/FETCH_ALL_MEMBERS_OF_TEAM_FAILED'

export const GET_MEMBER_PROFILE = 'MEMBERPAGE/GET_MEMBER_PROFILE'
export const GET_MEMBER_PROFILE_SUCCEEDED = 'MEMBERPAGE/GET_MEMBER_PROFILE_SUCCEEDED'
export const GET_MEMBER_PROFILE_FAILED = 'MEMBERPAGE/GET_MEMBER_PROFILE_FAILED'

