export const context = 'weeklyreport'

export const CREATE_WEEKLY_REPORT = 'WEEKLY_REPORTPAGE/CREATE_WEEKLY_REPORT'
export const CREATE_WEEKLY_REPORT_SUCCEEDED = 'WEEKLY_REPORTPAGE/CREATE_WEEKLY_REPORT_SUCCEEDED'
export const CREATE_WEEKLY_REPORT_FAILED = 'WEEKLY_REPORTPAGE/CREATE_WEEKLY_REPORT_FAILED'