export const context = 'weeklyreport'

export const GET_ALL_WEEKLY_REPORTS_OF_USER = 'WEEKLY_REPORTPAGE/GET_ALL_WEEKLY_REPORTS_OF_USER'
export const GET_ALL_WEEKLY_REPORTS_OF_USER_SUCCEEDED = 'WEEKLY_REPORTPAGE/GET_ALL_WEEKLY_REPORTS_OF_USER_SUCCEEDED'
export const GET_ALL_WEEKLY_REPORTS_OF_USER_FAILED = 'WEEKLY_REPORTPAGE/GET_ALL_WEEKLY_REPORTS_OF_USER_FAILED'


export const CREATE_WEEKLY_REPORT = 'WEEKLY_REPORTPAGE/CREATE_WEEKLY_REPORT'
export const CREATE_WEEKLY_REPORT_SUCCEEDED = 'WEEKLY_REPORTPAGE/CREATE_WEEKLY_REPORT_SUCCEEDED'
export const CREATE_WEEKLY_REPORT_FAILED = 'WEEKLY_REPORTPAGE/CREATE_WEEKLY_REPORT_FAILED'