export const context = 'reportpage'

export const FETCH_REPORTS = 'REPORTPAGE/FETCH_REPORTS'
export const FETCH_REPORTS_SUCCEEDED = 'REPORTPAGE/FETCH_REPORTS_SUCCEEDED'
export const FETCH_REPORTS_FAILED = 'REPORTPAGE/FETCH_REPORTS_FAILED'

export const FETCH_A_REPORT = 'REPORTPAGE/FETCH_A_REPORT'
export const FETCH_A_REPORT_SUCCEEDED = 'REPORTPAGE/FETCH_A_REPORT_SUCCEEDED'
export const FETCH_A_REPORT_FAILED = 'REPORTPAGE/FETCH_A_REPORT_FAILED'

export const CREATE_REPORT = 'REPORTPAGE/CREATE_REPORT'
export const CREATE_REPORT_SUCCEEDED = 'REPORTPAGE/CREATE_REPORT_SUCCEEDED'
export const CREATE_REPORT_FAILED = 'REPORTPAGE/CREATE_REPORT_FAILED'

export const UPDATE_REPORT = 'REPORTPAGE/UPDATE_REPORT'
export const UPDATE_REPORT_SUCCEEDED = 'REPORTPAGE/UPDATE_REPORT_SUCCEEDED'
export const UPDATE_REPORT_FAILED = 'REPORTPAGE/UPDATE_REPORT_FAILED'

export const DELETE_REPORT_SUCCEEDED = 'REPORTPAGE/DELETE_REPORT_SUCCEEDED'
export const DELETE_REPORT_FAILED = 'REPORTPAGE/DELETE_REPORT_FAILED'