export const context = 'authpage'

export const AUTH_LOGIN_REQUEST = 'AUTHPAGE/AUTH_LOGIN_REQUEST'
export const AUTH_LOGIN_SUCCEEDED = 'AUTHPAGE/AUTH_LOGIN_SUCCEEDED'
export const AUTH_LOGIN_FAILED = 'AUTHPAGE/AUTH_LOGIN_FAILED'

export const AUTH_LOGOUT_REQUEST = 'AUTHPAGE/AUTH_LOGOUT_REQUEST'
export const AUTH_LOGOUT_SUCCEEDED = 'AUTHPAGE/AUTH_LOGOUT_SUCCEEDED'
export const AUTH_LOGOUT_FAILED = 'AUTHPAGE/AUTH_LOGOUT_FAILED'