export const context = 'messagepage'

export const FETCH_ALL_MESSAGES = 'MESSAGEPAGE/FETCH_ALL_MESSAGES'
export const FETCH_ALL_MESSAGES_SUCCEEDED = 'MESSAGEPAGE/FETCH_ALL_MESSAGES_SUCCEEDED'
export const FETCH_ALL_MESSAGES_FAILED = 'MESSAGEPAGE/FETCH_ALL_MESSAGES_FAILED'

export const CREATE_MESSAGE = 'MESSAGEPAGE/CREATE_MESSAGE'
export const CREATE_MESSAGE_SUCCEEDED = 'MESSAGEPAGE/CREATE_MESSAGE_SUCCEEDED'
export const CREATE_MESSAGE_FAILED = 'MESSAGEPAGE/CREATE_MESSAGE_FAILED'
