export const context = 'teampage'

export const FETCH_ALL_TEAMS = 'TEAMPAGE/FETCH_ALL_TEAMS'
export const FETCH_ALL_TEAMS_SUCCEEDED = 'TEAMPAGE/FETCH_ALL_TEAMS_SUCCEEDED'
export const FETCH_ALL_TEAMS_FAILED = 'TEAMPAGE/FETCH_ALL_TEAMS_FAILED'
